### ISSUE TITLE
"brew install supergiant" should install supergiant locally

### ISSUE THREAD

**Issue by devrsw** [supergiant/supergiant#103]

**Comment by devrsw** [comment]
I've gone ahead and created a starting point for a homebrew formula, found here at  [homebrew-supergiant](https://github.com/supergiant/homebrew-supergiant). Would love to get some assistance there eventually.

**Comment by gopherstein** [comment]
A roadblock here... we will need to resolve our cross compile issues with gox before we will be able to automatically produce bins

**Comment by devrsw** [comment]
Ok, good to know. Going to close this issue here as we have the brew formula in a different repo.
