### ISSUE TITLE
Creating an admin user for the config file fails when user exists in DB

### ISSUE THREAD

**Issue by devrsw** [supergiant/supergiant#131]
Getting an error when generating a user/password via 

`go run cmd/generate_admin_user/generate_admin_user.go --config-file config/config.json`

`panic: UNIQUE constraint failed: users.username`

Is there a way for that command to detect if the user exists, and update the config file, or is the only solution to wipe the user record?

**Comment by FestivalBobcats** [comment]
This is no longer relevant as of #154
