### ISSUE TITLE
Bootstrap should be compiled from SASS

### ISSUE THREAD

**Issue by devrsw** [supergiant/supergiant#136]
In order for maximum flexibility down the road, we're going to be porting bootstrap from a css file into compiling from Sass.

**Comment by pjhampton** [comment]
Hey @devrsw 

I can take this forward if you haven't had the chance yet?

**Comment by devrsw** [comment]
@pjhampton for sure! Let me know if the folder structure makes sense to you. I've pushed an initial commit in the bootstrap-sass branch with the Bootstrap Sass files, and they'll need to be compiled into main.css and double-checked.

**Comment by devrsw** [comment]
Bootstrap is now compiled from Sass (there should be no visual changes at the moment). This lets us change bootstrap Sass variables in preparation for future UI work.
