### ISSUE TITLE
Wrong session credentials don't trigger any warning in UI

### ISSUE THREAD

**Issue by devrsw** [supergiant/supergiant#152]
Entering the wrong credentials just spits you back out to the sessions page.

**Comment by FestivalBobcats** [comment]
Do you not see this when you enter invalid input, or no input at all?

![image](http://g.recordit.co/OOle1WWoXW.gif)

**Comment by briansage** [comment]
That's what I see, including the error message. OSX Chrome 53.0.2785.116.
