### ISSUE TITLE
Request for multi-AZ kubes

### ISSUE THREAD

**Issue by weaseal** [supergiant/supergiant#161]
Request: Multi availability kubernetes clusters would give us additional peace of mind regarding single AZ failures.

**Comment by gopherstein** [comment]
This is in Progress.

**Comment by gopherstein** [comment]
@weaseal This is complete and will be closed when we pull. We need to do some QA testing on this before we pull, then it should be live.

**Comment by gopherstein** [comment]
@weaseal Sorry I am so late to respond to this... :-( We added this BTW.... 
https://github.com/supergiant/supergiant/commit/9c6d10a31d2d835efd0b4abdf17c07b8fb24db8a


Multi-AZ can be used like this:

    "public_subnet_ip_range": [
      {
        "ip_range": "172.20.0.0/24",
        "subnet_id": "",
        "zone": "us-east-1b"
      }
    ],

Adding "allowed" AZ is done by adding additional objects to this slice/array. The Supergiant autoscaler will round robin when building minions. NOTE: When choosing to use multi-AZ the user will need to take care while using EBS storage.
