### ISSUE TITLE
All supergiant AMI's are unavailable in us-east-2 (Ohio).

### ISSUE THREAD

**Issue by beckler** [supergiant/supergiant#165]
We're using us-east-2 (Ohio) for testing stuff, and we wanted to try out supergiant, but the AMI is unavailable in that datacenter. Github might not be the place to file this, but I didn't know where else to ask about it. If this is intended, that's fine, but I didn't see anything documented about it.

**Comment by briansage** [comment]
@beckler, thanks for making an issue.

This is a fine place to bring it up. You can also just drop by our Slack channel any time: https://supergiant.io/slack
