### ISSUE TITLE
Kube master bootstrap failing with region set to us-west-2

### ISSUE THREAD

**Issue by fabiocorneti** [supergiant/supergiant#168]
I installed `v0.13.1` on AWS in a VPC located in `us-west-2`, then configured the AWS admin credentials and created a new Kube with the following regional parameters:

- `aws_config.region`: `us-west-2`
- `aws_config.public_subnet_ip_range`: `us-west-2b`

All steps completed successfully but then Supergiant timed out waiting for Kubernetes API and first minion.

I SSHed to the master instance and saw no trace of Kubernetes in `ps aux`, so I tried to execute `/opt/bin/oneshot` manually; the curl command executed to download `master.yaml` is:

```
curl -s -H Date: Sun, 11 Dec 2016 17:58:03 +0000 \
-H X-AMZ-Security-Token: <token> \
-H Authorization: AWS <header> \
https://s3.amazonaws.com//kubernetes-kibi2/build/master.yaml \
-o /tmp/master.yaml
```

Which produced the following `/tmp/master.yaml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>kubernetes-kibi2</Bucket><Endpoint>kubernetes-kibi2.s3.amazonaws.com</Endpoint><RequestId>EAB6F5DDB9083FD4</RequestId><HostId>IdPIBfBuwvmv3I7iIdJsAqC3wPLdmXmNu01xkuX3rncoMaxqOdLvlWdQIDWgxiaSAuNK3Wff7b4=</HostId></Error>
```

This can be fixed by setting the region in the endpoint, replacing `s3.amazonaws.com/` with `s3-us-west-2.amazonaws.com` (the forward slash can be removed as it is part of `$RESOURCE`).

---

I also had an issue with `ssh-authorized-keys` in the same file; the parameter was set to:

```
ssh_authorized_keys:
  - ""
```

because the `ssh_pub_key` parameter is empty in the Kube definition returned by the Supergiant API. 

`cloudinit` will not parse the empty key, so I removed the parameter and the oneshot script executed correctly; `/home/core/.ssh/authorized_keys` contains the expected key (albeit twice).

**Comment by gopherstein** [comment]
We have a fix for the ssh key coming in our next update. If the ssh key is not specified in the AWS config json, the bootstrap can fail. The "ssh_pub_key" option in the aws config json must be populated with a correct, or dummy key in order to get around this currently. This is NOT intended behavior. In the new update if a key is not specified a dummy is supplied. This update was supposed to be released Friday, but there is a non-related kubernetes bug blocking it's release. I have been working thought this during the weekend and will have it out ASAP.

**Comment by fabiocorneti** [comment]
Actually the `/` in front of $RESOURCE is needed, I'm provisioning a Kube using the `aws_bug_patch` branch and it completes correctly by setting the region as follows in `config/providers/aws/bootstrap.yaml` (+ `go-bindata`):

```
# Download the file
curl -s -H "Date: ${DATE}" -H "X-AMZ-Security-Token: ${TOKEN}" -H "Authorization: ${AUTH}" "https://s3-{{ .AWSConfig.Region }}.amazonaws.com/${RESOURCE}" -o "/tmp/master.yaml"
```

**Comment by gopherstein** [comment]
nice. the aws_bug_patch branch has a bunch of updates. we are testing it right now actually before we merge... so if you see any glaring issues in the next while let us know.

**Comment by fabiocorneti** [comment]
I confirm that if I do not include the region in the curl command generated by bootstrap I can't deploy Kubes to regions different than `us-east-1`.

With the region set I've created Kubes in `eu-west-1`, `us-west-2` and `us-east-1`.

**Comment by fabiocorneti** [comment]
Here's the reference:

http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

So actually for `us-east-1` s3.amazonaws.com is the correct endpoint, but the other regions need to be specified explicitly.

**Comment by gopherstein** [comment]
This commit fixes the endpoint for all regions. https://github.com/supergiant/supergiant/commit/2101253436288776e441eb16425726555b57be67
