### ISSUE TITLE
Empty public_subnet_id in Kube JSON

### ISSUE THREAD

**Issue by fabiocorneti** [supergiant/supergiant#169]
On the same instance as #168 I tried to create an entrypoint but the action is not working because
the `public_subnet_id` parameter in the `aws_config` section of the Kube JSON is empty.

`aws_config.public_subnet_ip_range.subnet_id` holds the correct value, so I'm wondering if `public_subnet_id` is empty because of a bug; all the other parameters (`internet_gateway_id`, `vpc_id` etc.) outside of `aws_config` have the expected value; I can send you a JSON dump of the resource on Slack if that helps.

As a workaround I've created the ELB with the expected id and updated the `entrypoints` table manually in PostgreSQL, then I've been able to add listeners.

**Comment by gopherstein** [comment]
This has been resolved in our new update. This should be available asap. (hopefully tonight/tomorrow.)

**Comment by fabiocorneti** [comment]
Works fine after the recent modifications.

**Comment by gopherstein** [comment]
https://github.com/supergiant/supergiant/commit/2101253436288776e441eb16425726555b57be67
