### ISSUE TITLE
(supergiant) kubectl not working "cluster does not exist"

### ISSUE THREAD

**Issue by lohmander** [supergiant/supergiant#180]
When trying to use the kubectl with the supergiant cli, it consistently fails with the following error

```
▶ supergiant kubectl -k 3 get pods
Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
error: cluster "kubetest" does not exist
exit status 1
```

The cluster with id 3 (kubetest) certainly exists, and I'm not sure about the error message regarding api version.

All non-kubectl commands are working as expected.

**Comment by maikelvl** [comment]
The `--api-version` deprecation is just a warning (had it before).
Under the hood `supergiant kubectl` executes the following:

    kubectl \
        --api-version=v1 \
        --insecure-skip-tls-verify=true \
        --server=https://<master-ip> \
        --cluster=kubetest \
        --username=<username> \
        --password=<password>

To circumvent this warning, you could try downloading the kubectl binary and copy these settings in your `~/.kube/config` file. (https://kubernetes.io/docs/user-guide/kubeconfig-file/)

It seems your cluster is not bootstrapped properly. Try SSH into the machine and check the logs.

**Comment by FestivalBobcats** [comment]
@lohmander and the Kube finished provisioning, according to the UI?

**Comment by lohmander** [comment]
@FestivalBobcats Yes, all green.

**Comment by gopherstein** [comment]
@lohmander Are you setting the API key fro the CLI? `supergiant configure -s <server_address> -t <api_token> `

**Comment by lohmander** [comment]
@gopherstein Yes, I did set the api token as you described.

**Comment by FestivalBobcats** [comment]
@lohmander what is the output of `kubectl version`?

**Comment by lohmander** [comment]
I deleted my past supergiant setup. I did however setup a new now right now, and it seems to be working fine now. Only difference is I'm using latest version of SG and I'm using a 1gb master node instead of 512mb... Maybe unwise to try to use a 512mb master node to begin with?

Anyways, closing this issue since it seems to be working now.
