### ISSUE TITLE
1.0: Onboarding sequence dashboard + SGaaS (SuperGiant as a Service)

### ISSUE THREAD

**Issue by ChrisCates** [supergiant/supergiant#187]
Hey, I'm thinking we should also have an onboarding sequence on the dashboard.

I am even debating making a new proposal UX. One of my designers I can work with to make an amazing UX that clearly conveys what Supergiant does. I focus on the technical stuff, and he focuses on the front end design.
 
Links to the tutorials on the dashboard as well as the site.
We can also provide SGaaS (SuperGiant as a Service) and sell distributed cluster managers at a fee.

**Comment by FestivalBobcats** [comment]
We're definitely open to UX proposals. Feel free to drop mockups / finished designs in here, or make frontend code changes and PR.

**Comment by gopherstein** [comment]
Closing due to age, This onboarding process exists for 1.o and a new version is also being implemented in the 2.0 beta.
