### ISSUE TITLE
CPU and RAM usage metrics empty for DigitalOcean nodes

### ISSUE THREAD

**Issue by lohmander** [supergiant/supergiant#189]
Not sure if this is supposed to work with the current DO provider, but might as well track the feature.

Currently:
![screen shot 2017-01-23 at 09 58 15](https://cloud.githubusercontent.com/assets/2197050/22197522/a21c51b0-e152-11e6-8bf1-27452e557d53.png)

**Comment by FestivalBobcats** [comment]
This is an issue currently affecting all providers. Heapster/InfluxDB is the culprit -- Supergiant gets an error similar to the one mentioned [here](https://github.com/kubernetes/heapster/issues/1477) when trying to pull metrics from Heapster.

**Comment by TheKLARKEN** [comment]
This is resolved with the new UI.
