### ISSUE TITLE
Multi-master etcd error

### ISSUE THREAD

**Issue by maikelvl** [supergiant/supergiant#193]
As mentioned in https://github.com/supergiant/supergiant/issues/179

I've followed [the kubernetes on AWS tutorial](https://supergiant.io/blog/auto-scaling-kubernetes-cluster-on-aws-ec2-with-supergiant) with the addition of `kube_master_count`.

After creating a new kube config with setting `kube_master_count` to 3 on the AWS provider only the first EC2 instance got initialised. I found the following log from `journalctl` on this instance:

```console
error #0: client: etcd member https://discovery.etcd.io returns server error [Gateway Timeout]
```

I suspect this is caused by the fact that etcd can't get consensus because the other two masters will get initialised when this first master is operating. It is [waiting for the 3rd one](https://github.com/coreos/bugs/issues/964). I assume kubernetes will start until etcd is accepting connections.

**Comment by gopherstein** [comment]
hmmm... so we have seen a few cases where the etcd cluster API goes down, and this error occurs. If you tear down and rebuild are you able to get everything to come up? I would like to find a different way to form the cluster programmatically other then hitting that API.... Any suggestions on how to do that?

**Comment by maikelvl** [comment]
I've tried a fresh rebuild 3 times and all failed with this same message.
Do you mean you don't want to rely on the discovery.etcd.io service?

It is possible to create a single-member etcd cluster first, and then add etcd members later on.

**Comment by gopherstein** [comment]
This branch is aimed at solving the issue. I am not sure what I was smoking when I wrote this feature way back... but through time or looking back on it... the logic was weird.. anyway. I have simplified the logic down.. One note on why the logic may have been weird is that multi-master has to support multi-AZ as well. So before we merge this fix, we will need to test the heck our of clusters that are: multi-master, multi-master+multi-AZ,and single master. 

I would even love to develop a single master -> multi-master upgrade path (that would be cool. 

https://github.com/supergiant/supergiant/tree/multi_master_bug

**Comment by gopherstein** [comment]
One question @FestivalBobcats had a while back specifically with the AWS cube config is if we are keeping the config simple and clear of any redundancy. I am going to try to ensure the options are as simple to use in the config as possible.

**Comment by gopherstein** [comment]
There is another intermittent issue here with the public discovery API. Sometimes it goes down. https://coreos.com/etcd/docs/latest/v2/admin_guide.html has doc on using a private discovery api based on the 1st member of the cluster. I am going to try to get this put in place.

**Comment by gopherstein** [comment]
@maikelvl @FestivalBobcats @briansage  I have a pull out that should clear this up I hope. instructions for how to use multi-master/multi-az are in the pull. I will add documentation once we checkout that all is well.
