### ISSUE TITLE
CoreOS reboot strategy 'best-effort' deprecation

### ISSUE THREAD

**Issue by maikelvl** [supergiant/supergiant#194]
Accidentally came across a deprecation warning of the reboot strategy:

```console
Reboot strategy "best-effort" is deprecated and will be removed in the future.
Please explicitly set the reboot strategy to one of [off reboot etcd-lock]
See https://coreos.com/os/docs/latest/update-strategies.html for details on configuring reboot strategies.
```

**Comment by gopherstein** [comment]
So we currently do not set a update strategy and OS versions are detected. The latest stable AMI is detected and used. Do you think we need to set a reboot strategy? I would think we should set to "off" at least for the masters.

**Comment by maikelvl** [comment]
So this [defaults to 'best-effort'](https://github.com/coreos/locksmith/blob/master/locksmithctl/daemon.go#L310).

Yes, I also think we should set the default to "off". Although it would be awesome to use this auto-update feature.
