### ISSUE TITLE
DigitalOcean - kube minion and master fail to start

### ISSUE THREAD

**Issue by StephenRadachy** [supergiant/supergiant#201]
On both the kubernetes master and minion, flanneld fails to start because early-docker.service doesn't exist. Running coreos 1298.5.0

journal gives me this for docker.socket:
```
Mar 04 15:29:30 mykube-master systemd[1]: Starting Docker Socket for the API.
Mar 04 15:29:30 mykube-master systemd[1]: Listening on Docker Socket for the API.
Mar 04 15:29:40 mykube-master systemd[1]: docker.socket: Failed to queue service startup job (Maybe the service file is missing or not a non-template unit?): Unit early-docker.service not found.
Mar 04 15:29:40 mykube-master systemd[1]: docker.socket: Unit entered failed state.
```

I followed these two tutorials (to reproduce):
- https://supergiant.io/blog/how-to-run-supergiant-server-digitalocean
- https://supergiant.io/blog/how-to-auto-scaling-kubernetes-cluster-digitalocean

I'm not super familiar with coreos, docker, flannel, or kubernetes, but I'd really appreciate help fixing this.

Thanks!

**Comment by gopherstein** [comment]
This issue appears to be an across the board issue on CoreOS, I see it with all clouds. Digging into it.

**Comment by gopherstein** [comment]
@StephenRadachy Looks like some weird change with drop-ins on CoreOS. I was able to resolve the issue by reducing the modifications we make on the docker service. Expect a new release today.

**Comment by StephenRadachy** [comment]
Awesome. Thanks @gopherstein!
