### ISSUE TITLE
1.0: missing note in tutorial (create sqlite)

### ISSUE THREAD

**Issue by naarani** [supergiant/supergiant#205]
inside section "Installation"

- Checkout the releases page for binaries on Windows, Mac, and Linux.
- Copy (and customize if necessary) the example config file, and run with:

CREATE an empy SQLITE database
sqlite3 development

**Comment by jordanrinke** [comment]
Thanks for the report, I am going to leave this open for now. We are refreshing all of the documentation, and I will close this with the PRs that reference this specific change later.

**Comment by gopherstein** [comment]
Closing this issue as the documentation was changed to favour Postgres for 1.0 (SQLite was unstable), 2.0 uses etcd for its data and this is also documented in developer docs.
