### ISSUE TITLE
1.0: Supergiant not showing objects created using kubectl

### ISSUE THREAD

**Issue by alterx** [supergiant/supergiant#206]
Hey guys, first of all, I want to thank you for open sourcing this great tool. It makes it a breeze to deploy `kubernetes` on AWS.

With that being said I'm having a small issue:

I created a cluster following the AWS [tutorial](https://supergiant.io/blog/auto-scaling-kubernetes-cluster-on-aws-ec2-with-supergiant) (with some help from @gopherstein in the slack channel). I was able to create the kube and access the master node. After that, I started creating some services, deployments, load balancers, etc using `kubectl create -f [filename].yaml`. You know, just standard stuff.

The issue is that although the objects are created (and I'm able to make use of them) they don't show up in the Supergiant dashboard. According to @FestivalBobcats the objects that aren't created using the supergiant dashboard are scanned but for me, they're not showing up.

This is not a deal breaker for us but it'll be nice to be able to see all those objects in the dashboard and since Ben said that you guys do scan those objects it looks like it's just a bug that can be fixed and not a new feature.

Again, thanks for delivering an amazing product!

**Comment by gopherstein** [comment]
This issue was corrected in 1.0 - closing due to age.
