### ISSUE TITLE
1.0: QUESTION:

### ISSUE THREAD

**Issue by uromahn** [supergiant/supergiant#207]
From the documentation it is not clear which version of k8s will be used. Looking at the providers folder, it appears that the k8s version for AWS, GCE, and DigitalOcean is coming from some config variable which itself is nowhere documented and unknown where it would come from. For OpenStack, the corresponding YML files seem to have version 1.2.0 hardcoded which is really old and outdated.
It would be great to have some documentation how the k8s version is being determined and which k8s version are even supported.

**Comment by gopherstein** [comment]
The version is set by an option in the tube config. https://github.com/supergiant/supergiant/blob/master/pkg/model/kube.go#L74

A known working version is set for each provider. You can play with adjusting this. I would like to develop a slightly more elegant way of pairing cube version configuration with their build artifacts: https://github.com/supergiant/supergiant/tree/master/config/providers

**Comment by uromahn** [comment]
Hi Mike - thanks for the time to answer this. However, I don't think you got my question, or I was simply not clear enough - my apologies for that.

So, let me try to re-phrase more specifically.

I am aware of the configuration setting in https://github.com/supergiant/supergiant/blob/master/pkg/model/kube.go#L74 since I found that. It looks like the "default" setting is k8s version 1.5.1.
I also found the yml files for the different provider. That's when this question actually was formed. For example, in the OpenStack provider (https://github.com/supergiant/supergiant/blob/master/config/providers/openstack/master.yaml) the k8s version is hard-coded to "K8S_VERSION=v1.2.0" which, as I mentioned, is quite old. Unfortunately, there is no mention anywhere why this specific version is hardcoded there and if it s possible to upgrade to version 1.5.1 for the OpenStack provider.
Also, as an example, in the GCE provider, the K8S_VERSION seems to be set via variable substitution with "K8S_VERSION=v{{ .GCEConfig.KubernetesVersion }}". Unfortunately, there is no mention of where this ".GCEConfig.KubernetesVersion" comes from. Maybe this is some standard golang feature but I am not that much familiar with golang (my apologies) since I am just starting to get into it.

I think, it would be great if such "trivial" things could be documented somewhere without people, such as me, having to dig through source code and possibly having to learn some specific features of a programming language, such as go.

And finally, since there is such a strong coupling between supergiant and k8s, IMHO, I believe it is an absolute must to document the k8s versions supergiant will be using and/or work on, don't you think so too.

**Comment by gopherstein** [comment]
The reason that this version is hardcoded, is that the OpenStack provider has not been updated yet to accept the template option that the other providers use. Our development bandwidth is limited, so we have been focusing on requests first. I will treat this issue as a request and push this up my priority list.  I agree on the documentation. Unfortunately it just comes down to time. We hope to be able to remedy this in the next few weeks as we have more time to focus on it. Right now we only have 3-4 contributors, so the more contributors we can get will speed things up.

**Comment by gopherstein** [comment]
For anyone reading this. Any suggestions, even how to better organize/produce documentation for our project as we code is greatly appreciated.

**Comment by uromahn** [comment]
Thanks for this further update and your candor - much appreciated.

**Comment by gopherstein** [comment]
Closing due to age
