### ISSUE TITLE
Supergiant exits when installing an incubator helm chart

### ISSUE THREAD

**Issue by fastjames** [supergiant/supergiant#210]
Supergiant appears to exit when I try to install a particular helm chart. Here's the procedure I used:

1. Follow tutorial to install supergiant AMI (0.14.3) on AWS EC2 instance. I used the recommended m4.large in us-west-2.
2. Create a kube, I left the defaults in place so it created 2 nodes in us-east-1.
3. Add the incubator helm repo, http://storage.googleapis.com/kubernetes-charts-incubator
4. From the "helm charts" page search for name:patroni
5. Launch the chart into the kube you created in step 2

After clicking the Save button in step 5, supergiant stops answering HTTP requests. Rebooting the supergiant container instance gets it running again.

Observed behavior: supergiant admin UI stops working, helm chart is not launched
Expected behavior: supergiant admin UI should continue to work, and it should launch the requested helm chart.

**Comment by gopherstein** [comment]
Any issues when you manually install the chart? From the master?

**Comment by fastjames** [comment]
I was able to install the chart from the CLI on the master, so that worked.

**Comment by alterx** [comment]
I'm having the exact same issue,
My settings are: 
1. T2.large EC2 instance with the supergiant AMI (0.14.3), region us-east-1
2. One m4.large node (also in us-east-1)

I tried to install Jenkins and the supergiant server went down, had to restart the service.
Logging into the master node and issuing the `helm install` command from there does work.

**Comment by gopherstein** [comment]
@alterx @fastjames Can you guys check the status of this bug on Alpha? There may be OTHER helm issues we find, but I guess we can take those as they come.

**Comment by fastjames** [comment]
I'm looking at the alpha now, and waiting for the list of apps to refresh with the incubator apps (I just added the repo). I'll try to launch the patroni chart once I can see it in the list.

**Comment by fastjames** [comment]
This was fixed.
