### ISSUE TITLE
If kube master fails to provision before timeout multiple are created

### ISSUE THREAD

**Issue by jordanrinke** [supergiant/supergiant#218]
If a kube master fails to provision within the action timeout, the action is retried which creates multiple instances (specifically with the OpenStack provider). In this case, a kube master was created with an image that failed to properly launch. The error was either not thrown or not acted upon. The action waited until time out and then attempted the action again until all quota resources were used in OpenStack and then a no more resources error occured which halted the SG kube setup. Additionally but separately timeout values and retry values should be configurable.

**Comment by gopherstein** [comment]
As to the first point. I have added wait for checks to prevent retry on build errors. This should fix the reported issue. However, until we have someone/somewhere to test it fully we will not know for sure. We can re-open this issue if we can get that in place and this is indeed NOT fixed. For the second point. I am not completely opposed to exposing configuration for timeouts somewhere. There are many timeouts though all providers. I think a feature request better detailing how this configurable timeout could be filtered down to all the wait timeouts should be made. Each current timeout is timed with the observed reasonable time + padding. I am open to changes to this but in a specific feature card. I am closing this for now. If we would like to move forward with the timeout feature lets plan it out.
