### ISSUE TITLE
all minion names are the same on DigitalOcean

### ISSUE THREAD

**Issue by sokoow** [supergiant/supergiant#231]
I just discovered that all minion node names when using digital ocean are the same and follow a convention kube_name-minion . Is this by design? Kube doesn't seem to be recognizing it as multiple nodes, rather one node.

**Comment by gopherstein** [comment]
Ahh... prob a bug. Simple fix though... I will get out a fix right away. Prob do a release with the fix in the morning.

**Comment by sokoow** [comment]
Yeah, I was adding nodes and then noticed that all have same hostname, maybe try to add a random hash at the end of each hostname (4 letters should be enough). Also, I notice that supergiant sometimes goes crazy and provisions me a node out of the blue while deleting previous one ? Any way to control that behaviour?

**Comment by gopherstein** [comment]
We will get a couple of sign offs and get this released asap. If you would like to sign off.. Feel free to run this branch manually to test.

**Comment by sokoow** [comment]
I'll wait for the release and retest it tomorrow evening Dublin time, cheers and thanks for quick reaction

**Comment by gopherstein** [comment]
sure, sorry for the silly bug.
