### ISSUE TITLE
bump heapster to 1.3.0?

### ISSUE THREAD

**Issue by sokoow** [supergiant/supergiant#233]
I noticed that you have a default heapster version of image: gcr.io/google_containers/heapster:v1.1.0, and when using horizontal pod autoscaler I'm getting:

```
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  2m		7s		7	{horizontal-pod-autoscaler }			Normal		MetricsNotAvailableYet	unable to get metrics for resource cpu: failed to unmarshal heapster response: json: cannot unmarshal array into Go value of type v1alpha1.PodMetricsList
```

I suggest bumping it to 1.3.0 at least.

**Comment by gopherstein** [comment]
For anyone reading this you can set a heapster version with the "heapster_version" option in the kube config. That being said we will look at updating the default. 

Here is the model file that stores all possible kube config options: https://github.com/supergiant/supergiant/blob/master/pkg/model/kube.go

**Comment by gopherstein** [comment]
Actually it looks like we may have it set to immutable. Im not sure we will need to make that option variable as sticking with a recent version of heapster may be enough.

**Comment by gopherstein** [comment]
Hipster is now set at 1.4 by default.
