### ISSUE TITLE
JS user list polling appends to list

### ISSUE THREAD

**Issue by bfosberry** [supergiant/supergiant#338]
<img width="732" alt="screen shot 2017-09-12 at 9 34 15 am" src="https://user-images.githubusercontent.com/1553039/30337577-91d9c61e-979d-11e7-8775-45cd1631e898.png">

Also note the pagination links at the bottom

This is for ui/users

**Comment by gopherstein** [comment]
@bfosberry I have pushed a fix for this. Can you confirm all is well?

**Comment by bfosberry** [comment]
Looks great, thanks!
