### ISSUE TITLE
Json validation lags by one key-press

### ISSUE THREAD

**Issue by bfosberry** [supergiant/supergiant#343]
<img width="248" alt="screen shot 2017-09-12 at 9 44 13 am" src="https://user-images.githubusercontent.com/1553039/30338026-074ac03c-979f-11e7-9970-f5edcfdfa90b.png">

When validating JSON it's possible to get into a state where the json validator form says json is not valid, however the json IS, and until another key is pressed the form stays red

**Comment by gopherstein** [comment]
Fixed

**Comment by bfosberry** [comment]
awesome!
