### ISSUE TITLE
422 error should be form validation

### ISSUE THREAD

**Issue by bfosberry** [supergiant/supergiant#344]
` "message": "Validation failed: Name: greater than max"`

When creating a new kube if the name is too long it returns a 422 error after closing the form. This should be a form validation or it should allow editing and resubmitting the form

**Comment by TheKLARKEN** [comment]
Hi, @bfosberry, thanks for bringing this up, in the new beta, the form field no longer allows typing anymore than the max characters, and the regular expression restricting this is displayed below the text box, so this is no longer a problem. I apologize for the delay in getting to you; let me know if this fixes the issue!

**Comment by TheKLARKEN** [comment]
Hi, @bfosberry, I'll go ahead and close this; let me know if anything else needs to be done.
