### ISSUE TITLE
1.0: Allow failed creations to be retried

### ISSUE THREAD

**Issue by bfosberry** [supergiant/supergiant#345]
```
AccessDenied: User: arn:aws:iam::assfsvsf:user/supergiant-test is not authorized to perform: iam:GetRole on resource: role kubernetes-master\n\tstatus code: 403, request id: abcdef
```

Failed kube provision attempts enter a failed state, however in the case of retryable errors like access, a retry button or copy button should be provided

**Comment by TheKLARKEN** [comment]
Hi, @bfosberry, on the new beta, a malformed request or immediate failure won't close the current form, allowing a user to retry submission of the kube creation. Would this fill the need you're speaking of?

Or would it be more like something where a kube is provisioning normally, fails after exiting the form, and then gives the option to retry with prior form data?

Thanks!

**Comment by TheKLARKEN** [comment]
It would also be nice, in addition to this, if failed helm releases could have a retry button, as well, instead of spamming the recurring service with retries.

As brought to out attention by @fastjames, this would be very much worth considering if/when we remove the recurring service.

**Comment by gopherstein** [comment]
This feature has been added to 2.0 - currently in beta.
