### ISSUE TITLE
Unable to delete kubes that failed to provision

### ISSUE THREAD

**Issue by bfosberry** [supergiant/supergiant#347]
<img width="737" alt="screen shot 2017-09-12 at 3 13 38 pm" src="https://user-images.githubusercontent.com/1553039/30350753-f95175f6-97cc-11e7-88fd-dbb1b4ebe964.png">
in ui/kubes I am unable to delete provisioning kubes or kubes that failed to provision

**Comment by gopherstein** [comment]
@bfosberry Can you provide the log output under "System" as to why they are not deleting?

**Comment by gopherstein** [comment]
@bfosberry Are you asking for a force delete here? meaning, "I don't care, remove it from the DB."

**Comment by bfosberry** [comment]
Oh looks like its been fixed! Works perfectly now
