### ISSUE TITLE
New helm charts don't appear after adding a repo

### ISSUE THREAD

**Issue by fastjames** [supergiant/supergiant#361]
I'd like to install an incubator chart, so I have added the repo 
http://storage.googleapis.com/kubernetes-charts-incubator

In my supergiant Helm repos list. However, the charts in this repo are not appearing in the list of installable apps. I tried this last week, then deleted and re-added the repo today with the same result.

**Comment by gopherstein** [comment]
@fastjames Add a slash on the end. I did that and your repo showed up in a min or so..

**Comment by fastjames** [comment]
As @gopherstein noted, I was missing a trailing slash in my repo URL.
