### ISSUE TITLE
Adding new AWS cloud account returns "Error : Unprocesable Entity"

### ISSUE THREAD

**Issue by fastjames** [supergiant/supergiant#373]
I tried to add my AWS credentials using the Simple form but I wasn't able to do so. Here's what I did:

1. Login to SG beta admin
2. Click on "Cloud Accounts"
3. Click on "New +"
4. Select " AWS - Amazon Web Services"
5. Fill in "AAAAAAAA" (without quotes) for Access Key
6. Fill in "abcd1234" (without quotes) for Secret Key
7. Fill in "aws" (without quotes) for Name
8. Click Save

I then tried Steps 1-4 plus clicking "Advanced" and inserting my credentials into the JSON, with the same result code.

**Comment by fastjames** [comment]
Using firebug, I was able to get a more detailed error message:

> {
>   "status": 422,
 >  "message": "Validation failed: RequestError: send request failed\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: x509: failed to load system roots and no roots provided"
> }

**Comment by gopherstein** [comment]
You are using beta?

**Comment by fastjames** [comment]
Correct, I'm logged into beta.supergiant.io.

**Comment by gopherstein** [comment]
Alright... Looks like the scratch container for ARM is missing the CA roots. I will update that :-/

**Comment by gopherstein** [comment]
Can you give it a try now?

**Comment by gopherstein** [comment]
This was a CA cert issue in the ARM SG build.
