### ISSUE TITLE
System Logs not appearing in admin UI

### ISSUE THREAD

**Issue by fastjames** [supergiant/supergiant#379]
When I click the "System" button in the admin UI (beta) the Logs pane is already selected. However, instead of seeing the logs I see this:

> No log file configured!
> Create file and provide path to --log-file at startup.

Being able to view these logs would be very helpful in troubleshooting my API requests.

**Comment by gopherstein** [comment]
Yeah, we removed the log file option thinking it would just go to stdout but that does not seem to be the case. I will find a better solution.
