### ISSUE TITLE
GET /load_balancers returns an empty list when LBs exist

### ISSUE THREAD

**Issue by fastjames** [supergiant/supergiant#411]
I recently created a helm release via the SG API, and the release included a Service of type LoadBalancer. This created an AWS ELB as expected (yay!). Now I need to know more about that ELB so I can do some DNS work; however, when I try to get all load balancers the response is an empty list.

I'm not sure what I can contribute for supporting documentation; here's a dump from inside my program (slightly obfuscated):

> response is %HTTPoison.Response{body: {:ok, %{"filters" => nil, "items" => [], "limit" => 25, "offset" => 0, "total" => 0}}, headers: [{"Content-Length", "81"}, {"Content-Type", "text/plain; charset=utf-8"}, {"Date", "Thu, 30 Nov 2017 20:50:23 GMT"}], request_url: "https://beta.supergiant.io/abcd12345678/
server/api/v0/load_balancers", status_code: 200}

I didn't get any other identifying info about the request, since it's just a GET.

**Comment by fastjames** [comment]
I still haven't completely solved this, but I did find an interesting note in some AWS documentation that mentioned a difference in API versions related to the different load balancer types:

> This reference covers the 2012-06-01 API, which supports Classic Load Balancers. The 2015-12-01 API supports Application Load Balancers and Network Load Balancers.

It looks like the query that worked for me (the 'aws' CLI tool) uses the older API version, while SuperGiant and others use the newer version.

**Comment by fastjames** [comment]
I think the queries from supergiant should be using the API version I need, based on this reference in the source code:

https://github.com/supergiant/supergiant/blob/538bfc2d44a2bf4366539871bd36fdb8f1420ddb/vendor/github.com/aws/aws-sdk-go/service/elb/service.go#L66

**Comment by fastjames** [comment]
To follow up on this, I have 2 Classic ELBs active in AWS now, and in the SG beta admin it says "No Load Balancers."

**Comment by gopherstein** [comment]
So the issue here is that there are two types of LBs. There are SG LBs, or cluster LBs (which are actually services, of type load balancer.) So the LBs have been there all along just under the Services list. I am going to go ahead and fix them to be in both to avoid confusion.
