### ISSUE TITLE
1.0: List of running apps misparses app version

### ISSUE THREAD

**Issue by fastjames** [supergiant/supergiant#412]
I deployed a chart called `engine-storefront` with version 0.4.3. In the admin, when I look at the list of 'Running Apps' the app name is listed as `engine` and the version is listed as `storefront`. I think the dash in the chart name is confusing something.

**Comment by gopherstein** [comment]
Do you see this in a non-private example? So I can recreate?

**Comment by gopherstein** [comment]
Closing due to age and response.
