### ISSUE TITLE
/ui/clusters/n still has tribbles

### ISSUE THREAD

**Issue by fastjames** [supergiant/supergiant#413]
In this case, "tribble" refers to the fact that I get a steady stream of new "fake-lb" entries in the Load Balancers section of this page and "fake app" enttries in the Apps section.

**Comment by TheKLARKEN** [comment]
Hey, @fastjames, 

This was fixed in an pull request, which you can now experience by pulling the latest commits from ui2000. Sorry for the long delay in notifying you!

https://github.com/supergiant/supergiant/pull/410

Can you confirm for me that this fixes the issue?

**Comment by fastjames** [comment]
I'm using the SG hosted beta, so I'll check there as soon as it has been updated.

**Comment by fastjames** [comment]
This appears to be fixed now.
