### ISSUE TITLE
1.0: [OpenStack] Provider is hardcoded to require an image called "CoreOS"

### ISSUE THREAD

**Issue by colin-nolan** [supergiant/supergiant#440]
The OpenStack provider is hardcoded to require an image with the name "CoreOS":
https://github.com/supergiant/supergiant/blob/ae5fe4b6d9cece77493c3837073bfe6cd541c103/pkg/provider/openstack/create_kube.go#L110-L116

A configurable name should be used here.

**Comment by gopherstein** [comment]
For 1.0 this is expected behaviour. We will have more customizable settings for 2.0. In order to reduce complexity for provisioning, they use must make sure that the coreOS image exists under this name. For 2.0 the user will be able to specify any OS type they wish.
