### ISSUE TITLE
1.0: Security groups aren't configurable for OpenStack kubes

### ISSUE THREAD

**Issue by TheKLARKEN** [supergiant/supergiant#442]
As noted by @jrandall, there is currently no way for OpenStack users to have Supergiant configure security groups for their kube during provisioning. This means that if a user's default is to deny traffic, the kube won't be able to communicate. @jrandall would be able to give more insight on this and how/why it works this way.

Currently, we need to set up an OpenStack testing environment to work on this, which may take a few weeks to nail down.

Any feedback in the meantime as to how OpenStack users would like this to function would be very awesome!

**Comment by colin-nolan** [comment]
@TheKLARKEN I'm working on getting Supergiant working with our OpenStack platform today (I'm part of @jrandall's team). I don't know anything about how to set up an OpenStack testing environment but I'll be happy to test things out against our platform.

**Comment by gopherstein** [comment]
Closing due to age. Please re-open if this is still an issue.
