### ISSUE TITLE
1.0: Using Docker to build for distribution - question and suggestion

### ISSUE THREAD

**Issue by colin-nolan** [supergiant/supergiant#448]
I notice that you have a Dockerfile that builds Supergiant binaries: https://github.com/supergiant/supergiant/blob/master/build/Dockerfile.build. The products in `dist/bin` appear to work in Alpine but not Ubuntu. What is the purpose of these builds as it doesn't look like they're for general use?

As for the packaging for general distrubtion (as seen in https://github.com/supergiant/supergiant/blob/master/.travis.yml): it would be great if the builds were done in Docker, opposed to being coupled to Travis CI.

**Comment by TheKLARKEN** [comment]
Hi, @colin-nolan, the Dockerfile is an old contribution to the project, and we would be interested in knowing how you think it should be set up. There are probably some things we need to clean up in there, we're open to your suggestions.

**Comment by colin-nolan** [comment]
I'm interested in getting copies of the binaries through the same process as you guys use for distribution, without having to install/configure anything on the build machine (as it will undoubtly get configured differently). Docker therefore seems like a great idea.

The build process could happen as part of the Docker build or on container run + source mount (I've not read up on what best practice is). The ability to define a subset of the platforms to build for would be a nice to have.

**Comment by gopherstein** [comment]
1.0 uses a golang container now for a correct build on multiple platform types. 2.0 will follow this same process.
