### ISSUE TITLE
[AWS] InvalidInternetGatewayID.NotFound when creating cluster

### ISSUE THREAD

**Issue by fastjames** [supergiant/supergiant#449]
Today I attempted to create a new cluster via the SG beta admin. I checked the "raw data" and saw the following error:

>    {
>  "id": 4,t.
>  "uuid": "0d98c481-3154-40e0-a7e3-f9359f4c160a",
>  "created_at": "2018-03-16T15:41:19.74221Z",
>  "updated_at": "2018-03-16T15:41:59.644599Z",
>  "status": {
>    "description": "provisioning",
>    "max_retries": 20,
>    "retries": 17,
>    "error": "InvalidInternetGatewayID.NotFound: The internetGateway ID 'igw-7d895105' does not exist\n\tstatus code: 400, request id: ",
>    "total_steps": 37,
>    "steps_completed": 13
>  },

It appears that InvalidInternetGatewayID.NotFound is an error from AWS but I'm not sure what's causing it.

**Comment by TheKLARKEN** [comment]
It looks like it's due to the VPC limit (5), but the user wouldn't be able to see without access to the logs. We should add the component to see the logs, and we should create alert notifications based on errors.

**Comment by TheKLARKEN** [comment]
Root error addressed with giving users logs, but will also add better error messaging for the 1.0.0 release.
