### ISSUE TITLE
1.0: No validation of Kube `node_sizes` against core `node_sizes` for provider

### ISSUE THREAD

**Issue by colin-nolan** [supergiant/supergiant#451]
The documentation indicates that the Kube config node sizes must be a subset of those defined in the core settings, e.g. [DigitalOcean instructions](https://supergiant.io/blog/how-to-auto-scaling-kubernetes-cluster-digitalocean):
> "node_sizes": build an array of DigitalOcean node sizes chosen from sizes contained in the Supergiant config/config.json file...

Currently, however, it is possible to set any node sizes in the Kube config. If the sets are disjoint, an index out of range error will occur.

The node sizes in the Kube config should be validated if they are supposed to be a subset of the core defined node sizes.

**Comment by gopherstein** [comment]
This is resolved in 2.0, node sizes are being pulled from the provider API
