### ISSUE TITLE
1.0: Deployed helm releases disappear from 'Running Apps' list after deploy is complete

### ISSUE THREAD

**Issue by fastjames** [supergiant/supergiant#455]
Today I was able to successfully deploy my 2-chart stack, which is great. However, I noticed that after the app deploy was complete both helm releases disappeared from the "Deployed Apps" page in the supergiant admin UI.

**Comment by fastjames** [comment]
Details: I am deploying 2 charts, `stable/postgresql` and my rails app chart. Both charts appear on the list of Running Apps while they are in a state of deploying. Both charts then disappear from the list once their deployment is complete.

I wanted to try deploying a vanilla chart from the supergiant admin but I was unable to try that because the "Create Running App" page doesn't get any form field values filled in.

**Comment by gopherstein** [comment]
The root cause is that they disappear if they fail. 

What should happen is that the user should get some sort of failed notification.

**Comment by gopherstein** [comment]
These failed notifications now exist on 1.0 and 2.0
