### ISSUE TITLE
1.0: Helm release create returns error "command needs 1 argument: chart name"

### ISSUE THREAD

**Issue by fastjames** [supergiant/supergiant#464]
This morning I was able to create a k8s 1.8.7 cluster in the latest supergiant beta admin. I then attempted to create a helm release from the `stable/redis` chart. When I did so, I observed this error at the end of the helm run:

stable\" has been added to your repositories\nError: This command needs 1 argument: chart name\n

I have sent you the full JSON as a private gist since it may contain private information.

**Comment by fastjames** [comment]
I am pretty sure that the cluster is operational, as I was able to create a helm release of `traefik` via the CLI on the master node.

**Comment by gopherstein** [comment]
I think this is fixed now with this pull. https://github.com/supergiant/supergiant/pull/465

We will release again, and you can check for sure.
