### ISSUE TITLE
1.0: Openstack improvement pull requests

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#489]
These pull requests, unfortunately, have to be rejected due to CLA conflicts. I am recording them here and with our team project management tools, to have them re-created. 

https://github.com/supergiant/supergiant/pull/446
https://github.com/supergiant/supergiant/pull/444
https://github.com/supergiant/supergiant/pull/441

We will get these re-opened and merged as soon as possible. We apologize for the inconvenience.

**Comment by MrDienns** [comment]
What's the status on this?
