### ISSUE TITLE
Proposal: Entrypoint Logic

### ISSUE THREAD

**Issue by spankenstein** [supergiant/supergiant#52]
When a release gets deployed and has a public port specified a entry point should automatically create. 

if public = true && entry point ID == nil, a random entry point ID is created. 
if public - true && entry point ID != nil, the requested entry point gets created. 

The only thing here... would be if the user miss spells the entry point and accidentally makes one..

**Comment by FestivalBobcats** [comment]
> if public = true && entry point ID == nil, a random entry point ID is created.

Does the solution proposed in #39 solve your issue there? (it's a known bug right now)

> if public - true && entry point ID != nil, the requested entry point gets created.
> 
> The only thing here... would be if the user miss spells the entry point and accidentally makes one..

This one... kinda scares me. Creating an Entrypoint is trivial, and yeah, the misspelling issue you mention -- that's an $18/mo issue each time it happens undetected (I think that's the cost on AWS).

_NOTE currently you will see non-fatal error output related to Entrypoints missing when deploying. This should not happen. Entrypoints should be validated on Release create/update, before deploy._

**Comment by spankenstein** [comment]
hmmm.. I think a non-fatal msg would be the best approach here. Im gonna close.
