### ISSUE TITLE
Create resource logic error

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#57]
When creating a resource, if there is a connection issue with the kubernetes api, the resource still gets added to ETCD, This is probably fine. But, trying to delete this resource will fail. I think the issue here, is that the api, may need to keep track of the success of the create against the kube api? I am not sure what happens internally right now. But we have a few options.
1. error from the start, that there was a connection issue with kubernetes, and fail the create.
2. error from the start, and provisionally pass the create. (this would require the api to re-try the create later?)

**Comment by FestivalBobcats** [comment]
So, this is a complex issue, due to some resources provisioning synchronously, and others asynchronously. But, I think we're doing the best we can for now by _not returning errors when the Kubernetes resource is missing on deletes_. Going to close for now.
