### ISSUE TITLE
Which release file?

### ISSUE THREAD

**Issue by zwhitchcox** [supergiant/supergiant#594]
In the [tutorial](https://supergiant.io/blog/how-to-run-supergiant-server-digitalocean), it says to use the release file at [latest release](https://github.com/supergiant/supergiant/releases/tag/v1.1.0), but it does not say which one. Should I use the ui or the api?

**Comment by zwhitchcox** [comment]
Further errors on the tutorial (although, I'm not totally sure they're errors, because I don't know if I'm installing the right release):

when I run `sudo supergiant --config-file /etc/supergiant/config.json`, it tells me it's running on port 3001, whereas in the tutorial, it says 8080

It does not output the password when I first run it for the admin

**Comment by zwhitchcox** [comment]
Another bug in the tutorial, when I try to run the api release, I get 

root@supergiant:~# sudo supergiant --config-file /etc/supergiant/config.json
panic: sql: unknown driver "sqlite3" (forgotten import?) [recovered]
        panic: sql: unknown driver "sqlite3" (forgotten import?)

goroutine 1 [running]:
github.com/supergiant/supergiant/vendor/github.com/urfave/cli.HandleAction.func1(0xc4204df8f0)
        /home/travis/gopath/src/github.com/supergiant/supergiant/vendor/github.com/urfave/cli/app.go:478 +0x23b
panic(0x18200a0, 0xc42031a4b0)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505 +0x229
github.com/supergiant/supergiant/pkg/core.(*Core).Initialize(0xc420662000)
        /home/travis/gopath/src/github.com/supergiant/supergiant/pkg/core/core.go:109 +0xdb
main.main.func1(0xc4203488c0)
        /home/travis/gopath/src/github.com/supergiant/supergiant/cmd/server/server.go:35 +0x33
reflect.Value.call(0x172cac0, 0xc42031a140, 0x13, 0x1b24b72, 0x4, 0xc4204df8b0, 0x1, 0x1, 0xc420076040, 0x1ae7be0, ...)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x172cac0, 0xc42031a140, 0x13, 0xc4204df8b0, 0x1, 0x1, 0x2, 0x1, 0xc420322850)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/reflect/value.go:308 +0xa4
github.com/supergiant/supergiant/vendor/github.com/urfave/cli.HandleAction(0x172cac0, 0xc42031a140, 0xc4203488c0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/supergiant/supergiant/vendor/github.com/urfave/cli/app.go:487 +0x16d
github.com/supergiant/supergiant/vendor/github.com/urfave/cli.(*App).Run(0xc420599080, 0xc420038090, 0x3, 0x3, 0x0, 0x0)
        /home/travis/gopath/src/github.com/supergiant/supergiant/vendor/github.com/urfave/cli/app.go:245 +0x4d0
main.main()
        /home/travis/gopath/src/github.com/supergiant/supergiant/cmd/server/server.go:177 +0xc0c

**Comment by zwhitchcox** [comment]
Ok, that would be great, thanks! I didn't see that anywhere in the docs though, but i agree installation should probably be a high priority...please let me know when it is ready!

**Comment by TheKLARKEN** [comment]
Thanks for letting us know it was giving you trouble, too. 🙂 Every extra voice helps us prioritize these glaring issues! 🙂 I'll update you as soon as I can!

**Comment by TheKLARKEN** [comment]
The docs have been updated! https://supergiant.readme.io/v1.1.0/docs/linux

Hopefully this satisfies this particular issue. If there's no need to keep this issue open, I'll close it. Regarding #596, I'd like to leave it open for now, as a solution for it is still in the pipeline.

**Comment by zwhitchcox** [comment]
Nope, all good, thanks!
