### ISSUE TITLE
1.0: upgrade to v1.11.0 kubernetes and helm 2.9.1

### ISSUE THREAD

**Issue by zwhitchcox** [supergiant/supergiant#626]
Both 1.8.7 and helm 2.8.2 are incompatible with the latest version. It seems like these should be upgraded.

Simply running `helm init --service-account tiller --upgrade` appears to break helm completely, probably due to kubernetes being outdated.

**Comment by TheKLARKEN** [comment]
Thanks for letting us know! 🙂 Could you add a few details on how I could specifically reproduce this? 🙂 I'm not sure I'm clear on exactly what's happening. If it's any help, we have a guide on [submitting issues](https://supergiant.readme.io/v1.1.0/docs/github-issues).

**Comment by gopherstein** [comment]
Closing due to no response. Please re-open with further details if this is still an issue.
