### ISSUE TITLE
1.0: Improve code coverage

### ISSUE THREAD

**Issue by MrDienns** [supergiant/supergiant#649]
This project looks very promising in terms of functionality, but right now the coverage is only 39%. Having a piece of software responsible for hardware scaling & possibly / partly provisioning machines, I find it most logical that this project needs a much higher code coverage with proper test cases & assertions just to guarantee us as users as well as the team members that certain functionalities keep working. Coverage right now is about 39%, and I would personally like to see this raised up to at least 90%.

**Comment by egopher** [comment]
@MrDienns Thank you! This is what we have in our timeline. For the past two months we've been going trough the process of project redesign to achieve better scaleability and stability. Also, please notice that some features are covered by integration tests in test/ package which isn't counted towards general coverage.  If you have additional questions ping me or @TheKLARKEN via supergiant slack or email.

**Comment by gopherstein** [comment]
I am going to close this issue for now. Our code coverage goal, for now, is 70% and the team will continue to improve this. We can re-open after the launch of 2.0 with specific coverage concerns. But for now, this is included in project planning.
