### ISSUE TITLE
When setting external port to 0, the api should record the generated nodeport in etcd.

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#66]
When a user chooses to let kubernetes randomly assign a external port number, the port number generated by kubernetes should be stored in etcd, so the client side apps can construct a URL based on entry point/port.

**Comment by FestivalBobcats** [comment]
This information is displayed under component show route (/apps/:name/components/:name) under `addresses`.

Do you see it there?

**Comment by gopherstein** [comment]
Hey hey.... thank you sir. Added this to the describe comp view in the CLI :-)
