### ISSUE TITLE
When an external port is explicitly specified for a container port the port fails to work. 

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#67]
- The API creates the port, and adds it to the entry point as expected. 
- The port however does not actually route through to the pod.
- I have tested the nodePort directly and all is fine. This means the issue must be in the ELB configuration itself. Something in the port create on the ELB API does not translate packets from custom_port_num -> notePortNum

i.e. - if you create a component and set port 8088 -> 30xxx You will not be able to reach your app at http://elb:8088 however http://minion:30xxx works fine.

**Comment by FestivalBobcats** [comment]
Replied in Slack. You can test and see that this works with example.sh here:

https://github.com/supergiant/supergiant/blob/master/example.sh#L58

Are you able to reproduce the issue when you're using the API directly (and not the CLI)?

**Comment by FestivalBobcats** [comment]
Closed. #69 describes the problem now that we've hashed it out.
