### ISSUE TITLE
API needs to open ports for external_number when out of 30000-40000 range

### ISSUE THREAD

**Issue by FestivalBobcats** [supergiant/supergiant#69]
Kubernetes assigns NodePorts in the 30000-40000 range. Our Terraform build will open that range on the AWS Security Group.

If a user sets `external_number` on a Port to something outside of that range, the port will not be reachable due to being blocked by the Security Group.

The solution _may_ simply be to have the API open these ports on the SG, but need to discuss more with @gopherstein.

**Comment by gopherstein** [comment]
This is supported in this CLI commit: https://github.com/supergiant/supergiant-cli/commit/be02e2aeed34755afce77912af2510b666688655
