### ISSUE TITLE
UI broken on fresh install - Cannot find module "../elements/DeployButton.component"

### ISSUE THREAD

**Issue by mike503** [supergiant/supergiant#74]
Fresh install today, on AWS, using `bash <(curl -L https://supergiant.io/installer)`

Went to the Super Giant Dashboard URL: http://supergiant-supergiant-REMOVED.us-east-1.elb.amazonaws.com:30048

(removed my specific ELB address for privacy)

Due to this error, the UI won't show anything.

`Releases.component.js:27 Uncaught Error: Cannot find module "../elements/DeployButton.component"webpackMissingModule @ Releases.component.js:27(anonymous function) @ Releases.component.js:27(anonymous function) @ Releases.component.js:172(anonymous function) @ application.js:57n @ application.js:1(anonymous function) @ Releases.container.js:21(anonymous function) @ Releases.container.js:112(anonymous function) @ application.js:57n @ application.js:1(anonymous function) @ routes.js:51(anonymous function) @ routes.js:124(anonymous function) @ application.js:35n @ application.js:1(anonymous function) @ index.js:19(anonymous function) @ index.js:54(anonymous function) @ application.js:2n @ application.js:1(anonymous function) @ multi_main:2(anonymous function) @ application.js:1n @ application.js:1(anonymous function) @ application.js:1(anonymous function) @ application.js:1`

**Comment by esmevane** [comment]
Hey @mike503 - I've duplicated your issue here: https://github.com/supergiant/supergiant-dashboard/issues/110

I'm looking into it right now over there.  Thanks for the heads up!
