### ISSUE TITLE
2.0: Apps Store- Configure App text disappears

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/supergiant#768]
Summary of Issue:
Text in Configure App disappears

Steps to Reproduce:
1. Open the App store
2. View and App and click configure
3. Click out of the pop-up 
4. Reopen the configure again

Expected Results:
All text is there

Actual Results:
The box is blank

Dev Info: (fill out and add links to log files)
1. `1.10`
2. dddedff38267d34e16763fde1955ca4dec1cc5d7

**Comment by nikage** [comment]
fixed in #802
