### ISSUE TITLE
SG created a cluster with different key pair than specified one.

### ISSUE THREAD

**Issue by Jonnagurakala** [supergiant/supergiant#773]
Summary of Issue: During the creation of the cluster I had selected the key-pair but a new on was created by SG

Steps to Reproduce:

1:Opened the UI
2: Linked my AWS account.
3: Created a cluster with a single master and 0 nodes in the region us-east-1a
4:Then went to AWS console and realized it was a different key pair 

Actual Results:
Different key pair 

Dev Info: (fill out and add links to log files)

go version- "go version go1.9.3 darwin/amd64"
SG latest commit hash or release tag- "dddedff38267d34e16763fde1955ca4dec1cc5d7"
Number of Masters and Nodes-1 and 0
cloud provider-AWS
Logs from /tasks/{task_id}/logs/ws for all tasks spawned clusters- We cannot SSH into the master cause of another issue - that is a new key pair was created though another one was mentioned.
Log files from your local /tmp folder (these are named as .log-

```
time="2018-11-08T14:01:44-06:00" level=info msg="[aws_create_instance] - started"
time="2018-11-08T14:01:44-06:00" level=info msg="[aws_create_instance] - started"
time="2018-11-08T14:01:46-06:00" level=info msg="[aws_create_instance] - using AMI (ID: ami-10eadd6a) Canonical, Ubuntu, 17.10, amd64 artful image build on 2018-01-22"
time="2018-11-08T14:01:47-06:00" level=info msg="[aws_create_instance] - waiting to obtain public IP..."
time="2018-11-08T14:01:48-06:00" level=info msg="[aws_create_instance] - found public ip - 18.204.3.148 for node test-liki-master-1385"
time="2018-11-08T14:01:48-06:00" level=info msg="[aws_create_instance] - success! Created node test-liki-master-1385 with instanceID i-084023bfab1f90a3e"
time="2018-11-08T14:01:48-06:00" level=info msg="[aws_create_instance] - success"
time="2018-11-08T14:01:48-06:00" level=info msg="[ssh] - started"
time="2018-11-08T14:01:48-06:00" level=info msg="[ssh] - success"
time="2018-11-08T14:01:48-06:00" level=info msg="[download_kubernetes_binary] - started"
```

**Comment by gopherstein** [comment]
Fixed with: https://github.com/supergiant/supergiant/pull/804
