### ISSUE TITLE
2.0: UI- Similar named clusters interact

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/supergiant#777]
Summary of Issue:
WHen creating a cluster that has a name similar to an existing cluster, the provisioning screen for the new cluster is shared with the similarly named cluster if the similarly cluster had any failed tasks during spin up.

Steps to Reproduce:
1. Create a cluster named eldridge-do and when complete, create a cluster named eldridge-do1

Expected Results:
The cluster named eldridge-do1 provisioning screen only shows tasks for that cluster.

Actual Results:
The provisioning screen shows the current cluster and also shows the nodes and master from the similarly named cluster.

Dev Info: (fill out and add links to log files)
1. `go version`: 1.10
2. SG latest commit hash or release tag: dddedff38267d34e16763fde1955ca4dec1cc5d7
3. Number of Masters and Nodes: Any
4. cloud provider: DO

**Comment by eldridgeh** [comment]
@stgleb 
Clusters should receive unique id's during provisioning.

**Comment by gopherstein** [comment]
Fixed With: https://github.com/supergiant/supergiant/pull/847
