### ISSUE TITLE
2.0: AWS - Can not delete cluster

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/supergiant#781]
Summary of Issue:
You are unable to delete an AWS cluster

Steps to Reproduce:
1. Create an AWS cluster of any size
2. Click the delete cluster button

Expected Results:
The cluster is deleted

Actual Results:
Nothing happens

Dev Info: (fill out and add links to log files)
1. `go version`: 1.10
2. SG latest commit hash or release tag: dddedff38267d34e16763fde1955ca4dec1cc5d7
3. Number of Masters and Nodes: Any
4. cloud provider: AWS

**Comment by TheKLARKEN** [comment]
Likitha and I also noticed this. I noticed we also have this happen when the server crashes while a cluster is provisioning.

**Comment by TheKLARKEN** [comment]
Specifically, what we saw was:

```
INFO[0589] download_kubernetes_binary                   
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
```

When creating a cluster.
