### ISSUE TITLE
2.0: AWS UI Metrics/prometheus are not working

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/supergiant#782]
Summary of Issue:
After spinning up a cluster in AWS, the metrics bars for cpu  and ram never show up

Steps to Reproduce:
1. Spin up a cluster using AWS

Expected Results:
Prometheus is installed and metrics show up.

Actual Results:
Prometheus is never installed and metrics do not show up.

Dev Info: (fill out and add links to log files)
1. `go version`: 1.10
2. SG latest commit hash or release tag: dddedff38267d34e16763fde1955ca4dec1cc5d7
3. Number of Masters and Nodes: Any
4. cloud provider: AWS
[23a34f74-6754-4e6e-a53e-df346c456555.log](https://github.com/supergiant/supergiant/files/2563648/23a34f74-6754-4e6e-a53e-df346c456555.log)

**Comment by gopherstein** [comment]
Fixed with: #836
