### ISSUE TITLE
2.0: Tiller errors in the SG log

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/supergiant#785]
Summary of Issue:
After spinning up a cluster and logging off of my computer, once I come back, the UI doesn't see the local database. The Sg logs are filled with Tiller errors. This looks to happen mostly with AWS clusters. When this happens, the UI is not able to see the clusters in the clusters drop down. Clicking on any clusters shows a blank screen.

Steps to Reproduce:
1. Spin up some clusters.
2. Lock your computer or let it go to sleep

Expected Results:
Once you are back to your computer, you are able to connect to the db without any issue.

Actual Results:
All connection to the db is lost which breaks the UI. Tller logs show up in the SG db. This looks to happen when the pc is locked or falls asleep. We also see this error when spinning up AWS clusters.

Dev Info: (fill out and add links to log files)
1. `go version`: 1.10
2. SG latest commit hash or release tag: dddedff38267d34e16763fde1955ca4dec1cc5d7
3. Number of Masters and Nodes: Any
4. cloud provider: Any
[tiller_issue.log](https://github.com/supergiant/supergiant/files/2563715/tiller_issue.log)
`E1109 15:21:21.827371    5856 portforward.go:178] lost connection to pod
ERRO[0738] helm: list releases: eldridge-do cluster: list releases: rpc error: code = Unavailable desc = transport is closing 
ERRO[0738] helm: list releases: eldridge-do cluster: get kube: storage: get: entity not found `

[localhost-1541799130899.log](https://github.com/supergiant/supergiant/files/2567576/localhost-1541799130899.log)

This error really started to ramp up after the merge of :
https://github.com/supergiant/supergiant/commit/4b3c024a0a4c69f0b6d9dcdf42bb9ee7571e9734

After this merge, the error looks to happen randomly and quite frequently.

**Comment by gopherstein** [comment]
This issue appears to be resolved. We have not been able to reproduce it after TLS updates and Name conflict updates.
