### ISSUE TITLE
2.0: etcd install can randomly fail on multi master creation in DO

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/supergiant#787]
Summary of Issue:
When creating a 3 master 3 node cluster in DO , the master creation can fail during the etcd install.

Steps to Reproduce:
Create a 3 master 3 node cluster using DO.

Expected Results:
Everything provisions without issue.

Actual Results:
The master creation fails

Dev Info: (fill out and add links to log files)
1. `go version`: 1.10
2. SG latest commit hash or release tag: dddedff38267d34e16763fde1955ca4dec1cc5d7
3. Number of Masters and Nodes: 3 master, 3 nodes
4. cloud provider: DO

[do_etcd.log](https://github.com/supergiant/supergiant/files/2563787/do_etcd.log)
[do_etcd1.log](https://github.com/supergiant/supergiant/files/2563789/do_etcd1.log)

**Comment by gopherstein** [comment]
Does not appear to be happening any more. Maybe fixed by another pull? Please re-open if this happens again.
