### ISSUE TITLE
2.0: AWS - Unable to ssh into AWS boxes

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/supergiant#788]
Summary of Issue:
After creating a cluster on AWS, I am unable to ssh into the box.

Steps to Reproduce:
1. Spin up a cluster in AWS
2. Try to ssh into the master or a node.

Expected Results:
You are able to ssh into a box.

Actual Results:
You are unable to ssh in due to not having the PEM file.

Dev Info: (fill out and add links to log files)
1. `go version`: 1.10
2. SG latest commit hash or release tag: dddedff38267d34e16763fde1955ca4dec1cc5d7
3. Number of Masters and Nodes: Any
4. cloud provider: AWS

**Comment by gopherstein** [comment]
Fixed with https://github.com/supergiant/supergiant/pull/804
