### ISSUE TITLE
API should have a scope assignment for component->ports. 

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#79]
The api should allow users to specify a scope for component ports, indicating weather or not a service should be applied to all instances of a component, or if each component instance should get it's own service. The service names produced should be predictable, so that users can reference the DNS name for the desired service in the configuration of their application. 

An example use case: Configuring a multi-node mongodb cluster. 

MongoDB does not have a auto cluster discovery function. The mongodb master must be initialized with the DNS and port info of each member of it's cluster. Using this method, A user would be able to pass the DNS information for their cluster into the container ENV during launch, where a start script can consume and configure.

**Comment by FestivalBobcats** [comment]
Done in #91
