### ISSUE TITLE
Deleting target release causes 500 error

### ISSUE THREAD

**Issue by esmevane** [supergiant/supergiant#80]
Steps to reproduce:

1. Create an app
2. Create a component with a container, image: `ghost`
3. Prepare a release target
4. Deploy the release target
5. Prepare a new release target
6. Destroy release target

Two problems come up afterward - 

When trying to create a new release target:

<img width="541" alt="screen shot 2016-05-20 at 4 05 14 pm" src="https://cloud.githubusercontent.com/assets/263460/15442123/af431d18-1ea4-11e6-9165-67d0e29498ae.png">

When looking at the current release directly on the API:

<img width="772" alt="screen shot 2016-05-20 at 4 05 45 pm" src="https://cloud.githubusercontent.com/assets/263460/15442136/c0836290-1ea4-11e6-994b-2a9142915746.png">

**Comment by esmevane** [comment]
Attempted to restart the API (maybe the task queue started to hang for some reason?) and that didn't change anything.

**Comment by FestivalBobcats** [comment]
Just confirmed and this appears to be fixed. Not sure which push did it, but going to close this. You can reopen if you see it again @esmevane
