### ISSUE TITLE
Public UI: Fix background image on the blog

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#808]
![Screen Shot 2018-11-09 at 4:51 PM](http://marker.screenshots.prod.s3.amazonaws.com/4d5053366bd048d69acbc0b98d5f38dd-1541782315510.png)

**Summary:**
Background is not repeated or didn't have a gradient to the website's background color.

**Steps to Reproduce:** 
1. Go to supergiant.io
2. Hit "Blog" on the top menu
3. Scroll the page down 5 times (4-5 screens )

**Expected Results:** 
Background smoothly turns into the background color of the site.

---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [https://supergiant.io/blog/](https://supergiant.io/blog/)

<table><tr><td><strong>Browser</strong></td><td>Safari 12.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14</td></tr><tr><td><strong>Viewport Size</strong></td><td>1742 x 1025</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by gopherstein** [comment]
@hetmanchuk Is this resolved?

**Comment by hetmanchuk** [comment]
https://qboxio.slack.com/archives/CBJDVM0MQ/p1542537050177600

**Comment by gopherstein** [comment]
Reported as fixed via slack.
