### ISSUE TITLE
2.0: AWS: Prometheus step fails due to incorrect certificate generation.

### ISSUE THREAD

**Issue by egopher** [supergiant/supergiant#809]
Summary of issue:
Prometheus step on AWS fails because node IP's are not added to the alt-names in openssl.cnf during certificates generation step. 

Steps to reproduce: 
1) Provision one master, two nodes in AWS.
2) Wait till Prometheus step to begin. 

Possible workaround: 
Add skip_verify_check to the prometheus operator chart.  See https://github.com/coreos/prometheus-operator/issues/70

Dev Info: 
**Logs:** 
Error from server (AlreadyExists): serviceaccounts "tiller" already exists
Install tiller and wait for it to be ready
$HELM_HOME has been configured at /home/ubuntu/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
time="2018-11-09T18:36:00+02:00" level=info msg="[tiller] - success"
time="2018-11-09T18:36:00+02:00" level=info msg="[prometheus] - started"
Error: forwarding ports: error upgrading connection: error dialing backend: x509: certificate is valid for 34.205.246.93, 172.31.75.2, 10.3.0.1, 172.31.79.238ot 172.31.79.238
time="2018-11-09T18:36:02+02:00" level=info msg="[prometheus] - failed: install prometheus step: Process exited with status 1"

**Kubectl output**
root@ip-172-31-75-2:/etc/kubernetes/ssl# cat openssl.cnf
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = kubernetes.default.svc
DNS.4 = kubernetes.default.svc.cluster
IP.1 = 35.168.58.206
IP.2 = 172.31.75.2
IP.3 = 10.3.0.1
root@ip-172-31-75-2:/etc/kubernetes/ssl# kubectl get no -o wide
NAME               STATUS    ROLES     AGE       VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION      CONTAINER-RUNTIME
ip-172-31-74-67    Ready     <none>    3m        v1.11.1   172.31.74.67    <none>        Debian GNU/Linux 9 (stretch)   4.13.0-31-generic   docker://17.6.0
ip-172-31-75-2     Ready     <none>    6m        v1.11.1   172.31.75.2     <none>        Debian GNU/Linux 9 (stretch)   4.13.0-31-generic   docker://17.6.0
ip-172-31-79-238   Ready     <none>    4m        v1.11.1   172.31.79.238   <none>        Debian GNU/Linux 9 (stretch)   4.13.0-31-generic   docker://

**Comment by gopherstein** [comment]
Needs a owner.
