### ISSUE TITLE
2.0: UI - Should the 'delete cluster' button say 'cancel' while cluster is provisioning?

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#817]
![Screen Shot 2018-11-09 at 8:15 PM](http://marker.screenshots.prod.s3.amazonaws.com/556e0e32c7c24f9c8b659a44fd600132-1541794533729.png)
---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/aws-ldridge](http://localhost:4200/clusters/aws-ldridge)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1334 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr></table>

**Comment by eldridgeh** [comment]
This is working.
