### ISSUE TITLE
2.0: UI - The NEW link should be on top of the drop down and be renamed as 'CREATE CLUSTER'

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#823]
![Screen Shot 2018-11-09 at 9:29 PM](http://marker.screenshots.prod.s3.amazonaws.com/aa7cc0c48982475aa866db5ad0717a93-1541798979960.png)
---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/dashboard](http://localhost:4200/dashboard)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1610 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr></table>

**Comment by eldridgeh** [comment]
This is working
