### ISSUE TITLE
2.0: UI - You can move the UI around with your mouse. This shows a bunch of white space.

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#824]
![Screen Shot 2018-11-09 at 9:43 PM](http://marker.screenshots.prod.s3.amazonaws.com/ee4fa5c22d954d0f834b857786744868-1541799819279.png)
---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/dashboard](http://localhost:4200/dashboard)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1610 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr></table>

**Comment by josephkane** [comment]
@gopherstein @eldridgeh this is a browser thing that happens on all websites. can we close this?

**Comment by gopherstein** [comment]
This is normal behaviour. Closing.
