### ISSUE TITLE
Public UI: Change all absolute URLs to relative

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#831]
![Screen Shot 2018-11-10 at 12:10 PM](http://marker.screenshots.prod.s3.amazonaws.com/d1b5c016f4944737944dcf8fd01678e4-1541851852742.png)

**Summary:**
Need to change all absolute URLs like "http://qboxio.wpengine.com/support/" to relative like "/support/"

**Steps to Reproduce:** 
Go to home page http://supergiant.io/ and hit any button in the content area.

**Expected Results:** 
All elements with <a> tag have relative URLs like "/support/", "/toollkit/", etc

---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://supergiant.io/](http://supergiant.io/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.12.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 873</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment]
@gopherstein it's done
