### ISSUE TITLE
2.0: UI - We need to allow users to remove Apps

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#839]
![Screen Shot 2018-11-12 at 3:06 PM](http://marker.screenshots.prod.s3.amazonaws.com/2aa18d32ab384a8289762cb97b375c1c-1542035197573.png)
---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/do-eldridge](http://localhost:4200/clusters/do-eldridge)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1334 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by eldridgeh** [comment]
This is working
