### ISSUE TITLE
how I can specify a type of amazon instance during installation process of supergiant?

### ISSUE THREAD

**Issue by aliev** [supergiant/supergiant#84]

**Comment by gopherstein** [comment]
@aliev There should be a option to specify it in spacetime during cluster launch, but it looks like I did not expose it all the way. I will do that today and get back to ya.

**Comment by gopherstein** [comment]
This issue was moved to supergiant/supergiant-cli#9

**Comment by gopherstein** [comment]
Since this is a fault of the CLI, issue was moved to CLI repo.
