### ISSUE TITLE
2.0: UI - Put cluster name under metrics and replace with number

### ISSUE THREAD

**Issue by hetmanchuk** [supergiant/supergiant#841]
<img width="300" alt="sg_names_on_circle_clusters" src="https://user-images.githubusercontent.com/11389252/48360915-ef63f600-e6a8-11e8-9810-add0c1f6b6f7.png">

**Summary of Issue:**
We decided to place cluster name under metrics to avoid text overlaying and put cluster number (by date added) in the circle cluster with the only 1 number, e.g. 1, 2, 3, and so on. See example.

**Steps to Reproduce:**
1. Add minimum 1 cluster
2. Go to Home page of Supergiant Control
3. Switch to "Grid view" (not "Table view")

**It is very important to change it in all places where we can see circle with metrics and cluster name**

**Expected Results:**
Cluster name is under a circle (not in a circle), and in a circle we see "cluster number".

**Comment by josephkane** [comment]
Fixed by https://github.com/supergiant/supergiant/pull/857
