### ISSUE TITLE
2.0: UI - Link is blue when hovering over Apps in the breadcrumbs 

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#845]
![Screen Shot 2018-11-12 at 5:21 PM](http://marker.screenshots.prod.s3.amazonaws.com/f329f912446246ac98b8e97f32aefaf2-1542043311548.png)
---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/apps/supergiant/details/elasticsearch](http://localhost:4200/apps/supergiant/details/elasticsearch)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1334 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment]
@eldridgeh I can't reproduce it.

**Comment by gopherstein** [comment]
This is expected behaviour from the browser.
