### ISSUE TITLE
Load Balancer Name Too Long

### ISSUE THREAD

**Issue by mcrowson** [supergiant/supergiant#85]
When creating an entry point through the GUI, my entry point name was 22 characters long. It resulted in this error:

"ValidationError: LoadBalancer name cannot be longer than 32 characters status code: 400, request id: ..."

It saved my entry point and shows it in the list, but does not have an ELB address. When I attempt to delete this entry point, it shows the same error and will not delete the entry point.

**Comment by FestivalBobcats** [comment]
Sorry for the delay on this, @mcrowson, and thanks for the report. I've added a validation on the `domain` field in #93.
