### ISSUE TITLE
Public UI: Add <title> tag in HTML

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#850]
![Screen Shot 2018-11-13 at 12:42 PM](http://marker.screenshots.prod.s3.amazonaws.com/3e93089e3d19470289999d39d4ec9d53-1542112927882.png)
---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [https://supergiant.io/](https://supergiant.io/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment]
https://qboxio.slack.com/archives/CBJDVM0MQ/p1542537050177600

**Comment by gopherstein** [comment]
This was reported as fixed via slack.
