### ISSUE TITLE
2.0: UI - Change "DELETE CLUSTER" button to "Delete Cluster" text link with trash icon

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#851]
![Screen Shot 2018-11-13 at 1:00 PM](http://marker.screenshots.prod.s3.amazonaws.com/e857d48a577749488fc2ae38b42fca67-1542114016433.png)

**Steps to Reproduce:** 
1. Go to cluster details page
2. Scroll down to the end of a page

**Expected Results:** 
Button for cluster deletion changed with text link "Delete Cluster" with trash icon. Styling is similar as in Apps Store list page (text link "Remove repo")

---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://localhost:4200/clusters/taras-doclus](http://localhost:4200/clusters/taras-doclus)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment]
@josephkane Now I can see that we have "Cancel" button with the same styling... We can leave it "as is" I guess, what you think?

**Comment by josephkane** [comment]
@hetmanchuk I'm fine to leave this open if you would prefer it smaller, but maybe it can be a lower priority fix?

**Comment by hetmanchuk** [comment]
@josephkane Many people said that the button is awful/distracting, better to fix it now. Thanks.

**Comment by josephkane** [comment]
@hetmanchuk great. what should we do about the "cancel" button? same thing (trashcan) but with "cancel"?

**Comment by hetmanchuk** [comment]
@josephkane I can't see changes with "Delete" button. And "Cancel" let's leave as is for now.
