### ISSUE TITLE
2.0: UI - Change font-weight from thin (200) to regular (400)

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant#852]
![Screen Shot 2018-11-13 at 1:09 PM](http://marker.screenshots.prod.s3.amazonaws.com/8849ec22239b44208114190241a53ad0-1542114563281.png)

**Summary:**
Looks like we are using very thin font-weight, let's change all 200 to 400 (thin to regular), to be more similar to mockups

---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://localhost:4200/clusters/taras-doclus](http://localhost:4200/clusters/taras-doclus)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment]
@josephkane @nikage I think we don't need to do it with headers. But small sizes like 12-14-16-18 px should be changed to Regular weight (I guess it's 400 or 500).
