### ISSUE TITLE
2.0: API - Logs need timestamps

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/supergiant#859]
Summary of Issue:
SG logs need timestamps.

Steps to Reproduce:
Spin up a cluster and check the SG logs.

Expected Results:
Logs have a timestamp

Actual Results:
Logs do not have a timestamp

Dev Info: (fill out and add links to log files)
1. `go version` 1.10
2. SG latest commit hash or release tag : 2c4211a43c4ee6a39d0704485084dcf29cc1c05e
3. Number of Masters and Nodes: Any
4. cloud provider: Any

**Comment by gopherstein** [comment]
All SG tools should have log timestamps.
