### ISSUE TITLE
Constant Popup for Internal Server Error

### ISSUE THREAD

**Issue by mcrowson** [supergiant/supergiant#86]
This may be related to #85.

I keep getting a popup (once every second or two). "[500] 'http://supergiant-supergiant-######.us-east-1.elb.amazonaws.com/api/v0/tasks': Internal Server Error"

In addition, when I attempt to create a new component it just says "Internal Server Error" and will not save the component.

**Comment by mcrowson** [comment]
Following the troubleshooting guide of relaunching the cores yielded a 503:

$ supergiant delete core && supergiant create core
Core Install failed:  Request failed with status 503 Service Unavailable

**Comment by esmevane** [comment]
Hey @mcrowson the dashboard popup is absolutely related to the core install failure.  I notice you put in https://github.com/supergiant/supergiant/issues/85 as well.  Did the problems start right after the other issue?

**Comment by mcrowson** [comment]
Yes. I finally got the core delete and create to execute, but it did not stop the errors from popping up.

**Comment by esmevane** [comment]
It's possible that you have an older copy of the dashboard running which is still trying to hit the original core API.  Try refreshing it, and if for some reason it doesn't come up - look in your console for another fresh dashboard address and try that one instead.

**Comment by mcrowson** [comment]
Thought of that too :) It created a new ELB. I loaded that up and still got the internal server error.

**Comment by mcrowson** [comment]
I decided to remove supergiant. I don't think it is ready for us (or we're not ready for it). It looks super promising and appears to be the missing link in the container world for maximizing server use with auto-scalability. Going to keep an eye on it for sure, but I'm not going to be much help in troubleshooting this issue further.

**Comment by esmevane** [comment]
Sounds reasonable to me!  Thanks for giving us a hand, if you don't mind
I'm going to keep these issues open and we'll see if we can duplicate /
resolve them ourselves.  :)

**Comment by FestivalBobcats** [comment]
Closing this, since this can happen anytime the API crashes -- which unfortunately, was happening a lot in the past few versions. We will soon be displaying API log in the UI, and attempting to recover better.
