### ISSUE TITLE
2.0: API - AWS Instance types not showing on cluster details page.

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/supergiant#879]
Summary of Issue:
After #876 where we added instance sizes to the cluster detail page, AWS is not showing Instance sizes due to them not being returned. (this works with DO clusters)

Steps to Reproduce:
1. Create a cluster on AWS of any type/size
2. After creation got to the details page of the cluster

Expected Results:
The instance types are shown in the table on the details page.

Actual Results:
The instance types are not shown in the table on the details page.

Dev Info: (fill out and add links to log files)
1. `go version`: 1.10
2. SG latest commit hash or release tag: 300ea14416ebc16c176359f4decbe1648ea6d643
3. Number of Masters and Nodes: Any
4. cloud provider: AWS

**Comment by stgleb** [comment]
Closed by https://github.com/supergiant/supergiant/pull/936
