### ISSUE TITLE
2.0: API - DO - Unable to add a node to cluster

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/supergiant#883]
Summary of Issue:
We are unable to add a node to Digital Ocean.

Steps to Reproduce:
1. Create a cluster in DO
2. Add a node of any size

This was previously working.

Expected Results:
The node is added without issue.

Actual Results:
The node is not created and the attached error is thrown in the SG logs.
`INFO[0066] createMachineDigitalOcean                    
ERRO[0067] update kube state caused storage: get: entity not found 
ERRO[0067] update kube state caused storage: get: entity not found 
ERRO[0067] add node to cluster af394673 caused an error dropletService has returned an error in Run job: POST https://api.digitalocean.com/v2/droplets: 400 (request "90197717-a69c-4b2e-96bf-d2b264f8a9dd") Error validating resource tag: "tag-name \"\" contains invalid characters"`

Dev Info: (fill out and add links to log files)
1. `go version`: 1.10
2. SG latest commit hash or release tag: ba6ac33b7e5339f5355ef13a360190e6b0b2c4c5
3. Number of Masters and Nodes: Any
4. cloud provider: DIgital Ocean

**Comment by stgleb** [comment]
@eldridgeh Looks like tag name was invalid, what was cluster name?

**Comment by eldridgeh** [comment]
This is working
