### ISSUE TITLE
2.0: API - AWS create instance key pair error

### ISSUE THREAD

**Issue by stgleb** [supergiant/supergiant#896]
When provision cluster in AWS this error occurs during create instance step

```
has finished with error InvalidKeyPair.NotFound: The key pair 'glebaws3-provision
```

So at time instance is creating key-pair created for provisioning did not appear in API

**Comment by gopherstein** [comment]
The issue does not appear to be happening anymore. May have been fixed by an unrelated pull. Please re-open if this occurs again.
