### ISSUE TITLE
Public 2.0: UI - Change website logotype from PNG to SVG

### ISSUE THREAD

**Issue by hetmanchuk** [supergiant/supergiant#923]
**Summary**
<img width="1030" alt="homepage___supergiant1" src="https://user-images.githubusercontent.com/11389252/48699988-7f4af800-ebf3-11e8-8da2-c7bf8b415fcd.png">
<img width="1075" alt="homepage___supergiant2" src="https://user-images.githubusercontent.com/11389252/48699989-7fe38e80-ebf3-11e8-94f4-f3629ba55304.png">

Change all (landscape & portrait) Supergiant’s logotypes from PNG to SVG

**Steps to Reproduce:** 
Go to any page of [supergiant.io](https://supergiant.io/)

**Expected Results:** 
All logotypes in header and on the left side (when scrolling) are vector based SVG. 

**Notes:**
It is a gold standard for websites & apps for the last years.

**Comment by gopherstein** [comment]
This issue has been reported as resolved via slack.

**Comment by hetmanchuk** [comment]
@gopherstein it's not resolved by NOCT team, could you re-assign it to me? 
![image](https://user-images.githubusercontent.com/11389252/49938035-4693fb00-fee1-11e8-9e47-9216bb24daf0.png)
